language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-base' ]; then cd .. && eval "mv $currentfolder generator-angular-base" && cd generator-angular-base; fi

